Presentation/TalepYonetimi.Presentation/Controllers/ApplicationUserController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using TalepYonetimi.Application.Commands.ApplicationUsers;

namespace TalepYonetimi.Presentation.Controllers
{
    public class ApplicationUserController : Controller
    {
        private readonly IMediator mediator;
        public ApplicationUserController(IMediator _mediator)
        {
            mediator = _mediator;
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIn(string email, string password)
        {
            LoginApplicationUserCommand command = new()
            {
                Email = email,
                Password = password
            };

            var loginResult = await mediator.Send(command);

            if (loginResult.Succeeded == false)
            {
                ModelState.AddModelError("", "Giriş bilgileri hatalı.");
                return View();
            }

            return RedirectToAction("Success");
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(string name, string lastname, string username, string email, string phone, string password, string passwordConfirm)
        {
            CreateApplicationUserCommand command = new()
            {
                Name = name,
                LastName = lastname,
                UserName = username,
                Email = email,
                PhoneNumber = phone,
                Password = password,
                PasswordConfirm = passwordConfirm
            };
            var signUpResult = await mediator.Send(command);

            if (signUpResult.Succeeded == false)
            {
                ModelState.AddModelError("", "Kişi bilgileri kaydedilemedi.");
                return View();
            }

            return RedirectToAction("LogIn");
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

Presentation/TalepYonetimi.Presentation/Views/ApplicationUser/LogIn.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>GİRİŞ YAP</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                        <li class="breadcrumb-item active">Giriş Yap</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Giriş Yap</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" asp-controller="ApplicationUser" asp-action="LogIn" method="POST">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email</label>
                                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Emailinizi girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Şifre</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Şifrenizi girin">
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Giriş Yap</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-6">
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

Presentation/TalepYonetimi.Presentation/Views/ApplicationUser/SignUp.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>KAYIT OL</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                        <li class="breadcrumb-item active">Kayıt Ol</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Kayıt Ol</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" asp-controller="ApplicationUser" asp-action="SignUp" method="POST">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputName1">İsim</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputName1" placeholder="İsminizi girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputLastname1">Soyisim</label>
                                    <input type="text" name="lastname" class="form-control" id="exampleInputLastname1" placeholder="Soyisminizi girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputUsername1">Kullanıcı Adı</label>
                                    <input type="text" name="username" class="form-control" id="exampleInputUsername1" placeholder="Kullanıcı adınızı girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email</label>
                                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Emailinizi girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPhone1">Telefon</label>
                                    <input type="tel" name="phone" class="form-control" id="exampleInputPhone1" placeholder="Telefon numaranızı girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Şifre</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Şifrenizi girin">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPasswordConfirm1">Şifre Doğrulama</label>
                                    <input type="password" name="passwordConfirm" class="form-control" id="exampleInputPasswordConfirm1" placeholder="Şifrenizi tekrar girin">
                                </div>
                                @* 
                                <div class="form-group mb-0">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="terms" class="custom-control-input" id="exampleCheck1">
                                        <label class="custom-control-label" for="exampleCheck1">I agree to the <a href="#">terms of service</a>.</label>
                                    </div>
                                </div> *@
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Kayıt Ol</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-6">
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

Presentation/TalepYonetimi.Presentation/Views/ApplicationUser/Success.cshtml
<h1>İşlem başarılı!</h1>